### ISSUE TITLE
y

### ISSUE THREAD

**Issue by TWiStErRob** [TWiStErRob/ghlint-test#34]
### Reproduction steps

1. File `.github/workflows/x.yml` with the following content:
   ```yaml
   on: push
   jobs:
     repro:
       runs-on: ubuntu-latest
       steps:
         - run: echo "Problem!"
   ```

2. Run `ghlint` with the following arguments:
   ```shell
   ghlint --console .github/workflows/x.yml
   ```
c

### Expected behavior

a

### Actual behavior

b
